fix: pins cron (#1811)
`node-fetch` does not support `getReader` (or at least the version we were using does not):

```
 TypeError: stream.getReader is not a function
    at ndjsonParse (file:///home/runner/work/nft.storage/nft.storage/node_modules/@nftstorage/ipfs-cluster/src/index.js:627:25)
    at ndjsonParse.next (<anonymous>)
    at streamRequest (file:///home/runner/work/nft.storage/nft.storage/node_modules/@nftstorage/ipfs-cluster/src/index.js:332:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async statusAll (file:///home/runner/work/nft.storage/nft.storage/node_modules/@nftstorage/ipfs-cluster/src/index.js:202:20)
    at async file:///home/runner/work/nft.storage/nft.storage/packages/cron/src/jobs/pins.js:185:24
    at async mapAndQueue (file:///home/runner/work/nft.storage/nft.storage/node_modules/streaming-iterables/dist/index.mjs:836:27)
```